version: '3'

services:
  web:
    build: .
    image: app
    command: go run cmd/qapps/main.go -apikey=3059dd14799542e9a7b6ec5bf97dc62c
    volumes:
      - .:/go/src/github.com/AlexanderAsmakov/qapps
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db