version: '3'

services:
  web:
    build: .
    command: go run cmd/qapps/main.go
    volumes:
      - .:/go/src/github.com/AlexanderAsmakov/qapps
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db